baseurl = "https://aipavilion.github.io"
languageCode = "en-us"
title = "aiPav"
subtitle = "How will Artificial Intelligence change Humanity?"
copyright = ""
theme = "secml"

paginate = 10
paginatePath = "page"

pageNotFoundTitle = "Not Found"
pageNotFoundDetail = "Your request was determined to be an adversarial example by our web server. This could be because you are evil, but it is most likely a bad link or mistyped URL."

# disqusShortname = "evans1629"

[markup.goldmark.renderer]
unsafe= true

[permalinks]
    post = "/:slug/"
    code = "/:slug/"

[taxonomies]
    tag = "tags"
    topic = "topics"

[author]
    name = "aiPAV"
    #    email = "evans@virginia.edu"

[params]
    brand = "aiPAV"
    topline = "Pavilion Seminar: How will Artificial Intelligence change Humanity?"
    footline = "<p align=\"center\">PAVS 4500.04 | University of Virginia, Fall 2018 | <a href=\"https://www.cs.virginia.edu/evans\">David Evans</a></p>"
    sidebar = "left"
    googleAnalytics = "UA-3775212-1"

    nodate = true
    noauthor = true
    noread = true
    nopaging=true
    notoc=true

[blackfriday]
    angledQuotes = false
    fractions = false
    hrefTargetBlank = false
    latexDashes = true
    plainIdAnchors = true
    extensions = []
    extensionmask = []

[[menu.footer]]
